### ISSUE TITLE
apfs-fuse support old mac

### ISSUE THREAD

**Issue by eret1k** [sgan81/apfs-fuse#14]
Hi, I maked fork of your project https://github.com/eret1k/apfs-fuse and modify code for support old mac systems.
Maybe You will be adding mac support in your project, for crossplatform?

**Comment by tempelmann** [comment]
eret1k: Thanks for making the effort and sharing your changes.

However, there are a few things you could improve:

Please first remove all .DS_Store files and also update your user's .gitignore file (in your home folder) so that you never accidentally check them in again? Also, it would be nice if you'd enable Issues tracking on your fork so that others can make you aware of other issues.

And if you change files, you should keep them so that they still also fix for Linux. You cannot expect the person (e.g. sgan81) merging your changes to take care of that. For instance, your readme has erased all the Linux related info. You should instead make several sections so that there's one for Linux and one for macOS, keeping the original infos. And you apparently changed "replace __linux__ to __APPLE__" in many files - again, you should make the changes so that your version can still be compiled for Linux as well.

Otherwise, it makes it difficult to merge your changes into the sgan81's version. Which would lead to having two separate branches for Mac and Linux. That's not good at all in the long run.

If you make the changes, you could then use github's "Create Pull Request" button to have your changes merged into sgan81's more conveniently.

**Comment by RJVB** [comment]
This does beg the question why the current code is Linux-specific? Seems a bit surprising given the target (an Apple FS) and that FUSE is cross-platform...

**Comment by sgan81** [comment]
Well, Mac users can update to High Sierra in order to have APFS support ... ;-)

Actually, today I ported the whole thing to OS X. I was just able to test on 10.13 though. Feel free to test older versions and report if they are working or not.

**Comment by RJVB** [comment]
> Well, Mac users can update to High Sierra in order to have APFS support ... ;-)

Depends on the Mac - and isn't APFS exclusive to SSDs (in Apple's implementation)?

R.

**Comment by sgan81** [comment]
As I said, now the apfs-fuse should compile and run on macOS as well.

And no, APFS is not exclusive to SSDs. Only when a user is updating from 10.12 to 10.13, SSDs get converted to APFS, HDs and Fusion Drives don't. But you can in fact install macOS 10.13 on a HD formatted with APFS. I did it several times for testing purposes. It's just quite a bit slower than HFS+. Probably that's the reason why HDs don't get converted automatically yet. You can also create DMGs formatted with APFS.

**Comment by RJVB** [comment]
> As I said, now the apfs-fuse should compile and run on macOS as well.

Nice. What's the the minimum version? 

> And no, APFS is not exclusive to SSDs.

Good to know, but the performance bit is annoying, esp. about the Fusion drives. That really sounds like a missed chance and makes it a bit hard to believe that this performance difference won't translate to SSDs too.
Maybe APFS-Fuse is faster than the native deal on HDDs? ;)

Off-topic, but did you get a chance to compare performance of native APFS with ZFS (from o3x.org)?

R.

**Comment by sgan81** [comment]
I never compared APFS and ZFS performance-wise.

The slow performance on HDs when reading (writing is fast) is mainly due to the metadata blocks being spread over the whole device. This causes a lot of head movement on a HD, but isn't a problem on SSDs. Although I never tested APFS on an SSD.

I don't know the minimum version of macOS that supports apfs-fuse. It needs a compiler supporting C++11, that might be the limiting factor.

**Comment by eret1k** [comment]
Thank You very much for the added support of Mac.
I delete my fork.
You can propose add the driver to Homebrew repo.
