### ISSUE TITLE
Unable to get volume

### ISSUE THREAD

**Issue by renepickhardt** [sgan81/apfs-fuse#27]
Hey I asked [that question on stackexchange](https://apple.stackexchange.com/questions/323883/how-to-access-a-fusion-drive-from-ubuntu-linux-by-mounting-apple-core-storage) in which I already assumed that the filesystem from my mac might be broke. anyway the comment suggested to use your tool. 

following the calls like #3 I am not successful

``` root@ubuntu:/home/ubuntu/Downloads/apfs-fuse/build/bin# ./apfs-fuse -v 2 -d 1 /dev/sda /mnt/mac
Device /dev/sda opened. Size is 3000592982016
Found valid GPT partition table. Looking for APFS partition.
Unable to get volume! 
```

Do you have any suggestions? in any case #16  also holds for me. I consider myself not bad with computers but reverse engineering a file system and publishing the work is really great and far out of my skillset.

best Rene

**Comment by sgan81** [comment]
Is there any difference if you run it with -d 16?

**Comment by sgan81** [comment]
Also, you should probably use /dev/sda2, or whatever your APFS partition number is ... the partition scanner is intended for disk images.

**Comment by sgan81** [comment]
Just had a look at your stackexchange question ...

Are you sure your drive is not formatted in HFS+? Because fusion drives don't get converted to APFS when installing macOS 10.13. Also, if it was APFS, it would most probably not use CoreStorage.

Plus, I don't know how well CoreStorage is supported on Linux. CoreStorage is Apple's logical volume manager.

I find it somewhat strange though that even booting from the recovery partition causes a kernel panic. This should definitely not happen. But that is an Apple problem, obviously ...

**Comment by renepickhardt** [comment]
Hey sorry I oversaw your replays. I had the mac put to the applecare service. they installed a new version of my operation system and said the mistake came from a broken memory module which they have exchanged. 

Obviously their answers are .... 

however I don't have access to my old system anymore so I cannot reproduce anything. I would have assumed that I had APFS but as I said the people at apple just swiped everything. I guess this issue can be closed if my bug report didn't help. Might have very well been a problem on my side

**Comment by fredcooke** [comment]
Seems like this can be closed, @sgan81 ?

**Comment by sgan81** [comment]
I guess so ...
