### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by xajyvi** [sgan81/apfs-fuse#34]

**Comment by sgan81** [comment]
First question: sda1 is the EFI system partition, and is usually formatted as FAT-32. Usually, there's not much on it, except an EFI driver for APFS which allows the computer to boot from APFS volumes.

Regarding encryption, yes, there are blocks on the hard disk that contain encrypted keys. So in theory one could brute force them, but that would take an eternity due to the algorithms being used...

More precisely, the container superblock contains pointers to the key store if any volume is encrypted. That's how apfs-fuse detects encryption. See also ApfsLib/KeyMgmt.cpp.

You can mount the file system using -d 16, this will enable the dumping of the keys used for encryption (use carefully, and don't show the keys to anyone ... ;-) )
