### ISSUE TITLE
Bruteforce FileVault Encryption?

### ISSUE THREAD

**Issue by kepihu** [sgan81/apfs-fuse#35]
I've been getting into forensics and penetration testing lately and hoping you can help me understand what the below data is and how it might be used to perform a bruteforce attacks.

More specifically, what is "VEK Wrpd", "KEK Wrpd", "HMAC", and "PW Key"? And can they be used to reproduce the FileVault password if it's guessed correctly? 

	$ ./apfs-fuse -d 16 /dev/sda2/ /path/to/mount

	Device /dev/sda2 opened. Size is 250790436864
	starting LoadKeybag
	 all blocks verified
	 header has type 6b657973
	Volume macOS1 is encrypted.
	Password hint: looking for key type 3 for volume 1342XXXX-XXXX-XXXX-XXXX-XXXXXXXX4251 in m_container_bag
	Trying to load key bag from recs_block
	starting LoadKeybag
	 all blocks verified
	 header has type 72656373
	Password hint: looking for key type 4 for volume 1342XXXX-XXXX-XXXX-XXXX-XXXXXXXX4251 in recs_bag
	Enter Password: 
	GetVolumeKey: Dumping container keybag.
	Dumping Keybag (keys)

	Version :    2
	Keys    :    2
	Bytes   :       e0

	Key 0:
	UUID    : 1342XXXX-XXXX-XXXX-XXXX-XXXXXXXX4251
	Type    :    3 [Keybag Ref]
	Length  :   10
	Unknown :        0

	Block   :           7c1f57
	Count   :                1

	Key 1:
	UUID    : 1342XXXX-XXXX-XXXX-XXXX-XXXXXXXX4251
	Type    :    2 [VEK]
	Length  :   7c
	Unknown :        0

	[Blob Header]
	Unk 80  : 0
	HMAC    : 106BXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9921
	Salt    : 5493XXXXXXXX1F47

	[VEK]
	Unk 80  : 0
	UUID    : 1342XXXX-XXXX-XXXX-XXXX-XXXXXXXX4251
	Unk 82  :        0    1 9e b1
	VEK Wrpd: 06391FA9XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX552582F2

	GetVolumeKey: looking for key type 3 for volume 1342XXXX-XXXX-XXXX-XXXX-XXXXXXXX4251 in m_container_bag
	 key found
	 data size matches that of key_extent_t
	Trying to load key bag from recs_block
	starting LoadKeybag
	 all blocks verified
	 header has type 72656373
	Volume key bag loaded successfully. Dumping contents.
	Dumping Keybag (recs)

	Version :    2
	Keys    :    3
	Bytes   :      220

	Key 0:
	UUID    : 257AXXXX-XXXX-XXXX-XXXX-XXXXXXXX7975
	Type    :    3 [KEK]
	Length  :   94
	Unknown :        0

	[Blob Header]
	Unk 80  : 0
	HMAC    : F047XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXF6A8
	Salt    : 630CXXXXXXXX268

	[KEK]
	Unk 80  : 0
	UUID    : 257AXXXX-XXXX-XXXX-XXXX-XXXXXXXX7975
	Unk 82  :        0    2 9e b1
	KEK Wrpd: BB7FXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX07F8
	Iterat's: 100000
	Salt    : 863CXXXXXXXXXXXXXXXXXXXXXXXX2F51

	    
	Key 1:
	UUID    : CDF5XXXX-XXXX-XXXX-XXXX-XXXXXXXXE4CA
	Type    :    3 [KEK]
	Length  :   94
	Unknown :        0

	[Blob Header]
	Unk 80  : 0
	HMAC    : 5A2AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAEB8
	Salt    : BFBFXXXXXXXX5FD6

	[KEK]
	Unk 80  : 0
	UUID    : CDF5XXXX-XXXX-XXXX-XXXX-XXXXXXXXE4CA
	Unk 82  :        0    2 9e b1
	KEK Wrpd: 43A8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5E07
	Iterat's: 117590
	Salt    : 8751XXXXXXXXXXXXXXXXXXXXXXXXB0DA

	Key 2:
	UUID    : EBC6XXXX-XXXX-XXXX-XXXX-XXXXXXXXECAC
	Type    :    3 [KEK]
	Length  :   94
	Unknown :        0

	[Blob Header]
	Unk 80  : 0
	HMAC    : 9F92XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5706
	Salt    : E363XXXXXXXXCC09

	[KEK]
	Unk 80  : 0
	UUID    : EBC6XXXX-XXXX-XXXX-XXXX-XXXXXXXXECAC
	Unk 82  :        0    2 9e b1
	KEK Wrpd: CF35XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXEC04
	Iterat's: 127270
	Salt    : 3780XXXXXXXXXXXXXXXXXXXXXXXXA2E7

	PW Key  : EE62XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX6AB5
	KEK Wrpd: BB7FXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX07F8
	KEK     : A60EXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX4D78
	KEK IV  : F7ECXXXXXXXX202A

	PW Key  : 6363XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX6191
	KEK Wrpd: 43A8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5E07
	KEK     : EB9FXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXD6F9
	KEK IV  : 5932XXXXXXXX4ACB

	PW Key  : 6B62XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXEEFF
	KEK Wrpd: CF35XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXEC04
	KEK     : B579XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAD90
	KEK IV  : A3E7XXXXXXXXCA4F

  [1]: https://github.com/sgan81/apfs-fuse/issues/34

**Comment by sgan81** [comment]
Yes they can.

Basically, the encryption works as follows:

- Keys are encrypted and decrypted (wrapped / unwrapped) using the method described in RFC 3394.
- HMAC and salt in the blob header are just used to verify the blob contents (using HMAC-SHA256)

The VEK (Volume encryption key) is wrapped using a KEK (key encryption key), and then stored in the VEK blob.
The KEK is wrapped using a key that is derived from a password. The derivation method is PBKDF2-HMAC-SHA256. The wrapped KEK is then stored in a KEK blob.

So, Wrpd means wrapped. If a key is unwrapped (decrypted) correctly, the resulting IV should be A6A6A6A6A6A6A6A6.

However, deriving the key from the password is quite slow. As you can see, it uses around 100'000 iterations ... so that limits the usefulness of brute forcing.

The implementation of this is in ApfsLib/KeyMgmt and ApfsLib/Crypto.

**Comment by kepihu** [comment]
Wow. This is fascinating. It's amazing how well you understand these technologies. Thank you for your responses. May I continue to pick your brain?
> The implementation of this is in ApfsLib/KeyMgmt and ApfsLib/Crypto.

How do we view the ApfsLib/KeyMgmt and ApfsLib/Crypto if/when the harddrive is encrypted?

> deriving the key from the password is quite slow

The speed of password guessing attacks would depend on the CPU/GPU performance, right? I would be interested in benchmarking my CPUs/GPUs with such attacks, but I'm not sure how to turn the dumped info into something [John the Ripper](https://tools.kali.org/password-attacks/john)/Hashcat can interpret. Would you be able to show a simple password guessing attack using the "KEK Wrpd" and/or "PW Key" using John the Ripper?

**Comment by sgan81** [comment]
With ApfsLib/KeyMgmt and ApfsLib/Crypto, I was referring to the corresponding cpp/h source files. Crypto.cpp implements the RFC 3394 key wrapping, as well as HMAC-SHA256 and PBKDF2-HMAC-SHA256. Those are standard functions implemented by many crypto libraries as well.

So the keyspace is 2^256 possible keys. Approx. 2^192 of them will lead to a correct IV when deciphering the KEK. So if someone then tries to decrypt the VEK using the KEK, it will still get about 2^128 VEKs with the correct IV. So that's only of limited use to check if the key is correct.

As I said ...

- take a password
- Use PBKDF2-HMAC-SHA256 to derive the 256-bit password key ("PW Key") from it
- Use the derived key ("PW Key") to decrypt (RFC 3394) the wrapped KEK and check IV
- If IV correct, use decrypted KEK to decrypt (RFC 3394) the wrapped VEK and check IV
- If IV correct, try to mount the volume or whatever ...

If the wrapped keys contain 0s in the last 16 bytes, the decrypted keys are only 128 bits long, in which case unwrapping uses AES-128 instead of AES-256.

For brute forcing, you would need:
- Wrapped KEK (trying all of them might lead to the correct PW faster)
- Wrapped VEK
- Iterations and Salt, which is needed for PBKDF2. They are also in the KEK blob.

The VEK blob UUID is the volume UUID.
The KEK blob UUID is usually the UUID of the crypto user. But not always, so apfs-fuse just tries all KEKs available for a volume.

**Comment by trounce1** [comment]
Hi Kepihu i am looking at building an OpenCl bruteforcer for this encryption.

I cant seem to get the same output as you do.

Any idea how i get all the debug data to apear?

has it been patched out?

**Comment by sgan81** [comment]
Use the -d flag when mounting ... -d 16 should output pretty much everything ...

**Comment by trounce1** [comment]
ive realised ive been very stupid. i have just created an encrypted apfs dmg with disk utility and that is not the same at an image of a live apfs container as mine only contains the volume itself.

**Comment by kepihu** [comment]
@sgan81 thank you for your detailed explanation!

@trounce1, I boot the Macbook using a Debian live USB, install apfs-fuse and then used `-d 16` in the command. I look forward to seeing your bruteforcer develop!
