### ISSUE TITLE
Mounted filesystem gets root:root ownership

### ISSUE THREAD

**Issue by a-wai** [sgan81/apfs-fuse#61]
Issue occurred on Debian Stretch, with libfuse 2.9.7

When mounting an APFS filesystem with apfs-fuse, the whole filesystem's uid and gid are set to 0 (root ownership). This can prevent a regular user from accessing some files, or to use an overlayfs on top of an APFS filesystem.
When using the "uid=N" option to set the filesystem's user ID, fuse returns with the following message: `fuse: unknown option 'uid=N'.

This option seems not to be understood when using fuse_lowlevel_*, which means apfs-fuse has to do some option parsing to handle it.

**Comment by ajrossnz** [comment]
how do you mount as a normal user?

**Comment by sgan81** [comment]
The newest version now allows setting of uid and gid via mount options:
Example: ```apfs-fuse -o uid=1000,gid=1000 <device> <mount-path>```. If you mount as root and want normal users to be able to access the volume, add ```allow_other``` to the mount options.

You can only mount as a normal user if you have read access to the device. Adding yourself to the disk group is one possibility, but it is not too safe, because it allows any application to read and write anywhere on a disk.
